# Site settings
title: Becoming a Developer
header-img: img/home-bg.png
email: josh.kramer.dev@gmail.com
copyright_name: funemployeddad
description: > # this means to ignore newlines until "baseurl:"
  Living the Dream
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: FunEmployedDad
github_username:  funemployeddad
learn_profile: funemployeddad
email_username: josh.kramer.dev@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
